stages:
  - test
  - deploy

image: continuumio/anaconda3

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get update && apt-get install -y build-essential
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de".insteadOf "ssh://git@gitlab.lrz.de"
    - conda init bash
    - conda env create -f environment.yml
    - source activate cr-py38
    - conda info
    # - pip uninstall git+ssh://git@gitlab.lrz.de/cps/commonroad-stl-monitor.git@new-interface
    - conda install -c conda-forge cvxpy
    - pip install git+ssh://git@gitlab.lrz.de/cps/commonroad-stl-monitor.git@update-from-develop
    - pip install -r requirements.txt
    
test:
  stage: test
  only:
    - master
    - develop
  script:
    - pip install -e .
    - cd $CI_PROJECT_DIR/tests && python -m unittest


deploy_develop:
  when: manual
  only:
    - master
    - develop
  stage: deploy
  script:
    - pip install twine bump2version
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - bump2version build
    - python setup.py sdist bdist_wheel --universal
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload  --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    - git remote set-url origin "https://gitlab-ci-token:${VERSION_BUMP_PUSH_TOKEN}@gitlab.lrz.de/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
    - git push -o ci.skip origin HEAD:${CI_COMMIT_REF_NAME}

