stages:
  - test
  - deploy

image: continuumio/anaconda3

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - conda init bash
    - conda env create -f environment.yml
    - source activate cr-py37
    - conda info
    - cd external/commonroad-drivability-checker/ && ./build.sh -e /opt/conda/envs/cr-py37 -v 3.7 -i -j 64 --no-root

test:
  stage: test
  script:
    - pip install --index-url https://commonroad-repairer-package:DgzMqqqWWzECPsQpqDv6@${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi/simple  -e .
    - cd $CI_PROJECT_DIR/tests && python -m unittest

deploy_develop:
  when: manual
  stage: deploy
  script:
    - pip install twine bump2version
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - bump2version build
    - python setup.py sdist bdist_wheel --universal
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload  --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    - git remote set-url origin "https://gitlab-ci-token:${VERSION_BUMP_PUSH_TOKEN}@gitlab.lrz.de/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
    - git push -o ci.skip origin HEAD:${CI_COMMIT_REF_NAME}

