stages:
- test

image: continuumio/anaconda3
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
#cache:
#  paths:
#    - .cache/pip
#    - anaconda3/envs

before_script:
  - apt-get update && apt-get install -y cmake g++ libeigen3-dev libboost-all-dev
  - apt-get -y install gcc
  - apt-get install python3-dev
  - apt-get install ssh-client
  - conda init bash
  #- git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
  #- git submodule update --init --recursive  
  - conda env create -f environment.yml
  - source activate cr-py37
  - conda info
  - conda install -c conda-forge cvxpy
  # - cd external/commonroad-drivability-checker/ && ./build.sh -e /opt/conda/envs/cr-py37 -v 3.7 -i -j 64 --no-root
  # - cd external/stl_crmonitor/ && git submodule update --init --recursive && pip install external/rtamt && conda develop .
  - conda develop $CI_PROJECT_DIR
  - git submodule deinit --all --force # Enforce that the submodules are not cached before changing them
  - sed -i "s/git@gitlab.lrz.de\/yuanfei\/commonroad-qp-planner.git/https:\/\/gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de\/yuanfei\/commonroad-qp-planner.git/" .gitmodules
  - git submodule init
  - git submodule sync
  - sed -i "s/git@gitlab.lrz.de:cps\/commonroad-drivability-checker.git/https:\/\/gitlab-ci-token:${CI_PROJECT_TOKEN}@gitlab.lrz.de\/cps\/commonroad-drivability-checker.git/" .gitmodules
  - more .gitmodules
  - git submodule init
  - git submodule sync --recursive


build_and_test_python_3_7:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - python setup.py install
    - cd $CI_PROJECT_DIR/tests && python -m unittest
