debug:
  show_plots: true
  # save_plots: true
  plot_limits: [-5, 50, -4.5, 3]
repair:
  ego_id: 202
  rules: ["R_G3"]
  planner: 2         # 1: qp, 2: miqp
  t_0: 0             # initial time step
  N_r: 21            # number of time steps
miqp_planner:
  slack_long: False
  weight_long: [0.1, 0.4, 1, 2, 0.1, 1000000] # s, v, a, j, u, slack
  weight_lat: [0.05, 15.1, 40.0, 20.0, 1.0, 0.1] # d, theta, kappa, kappa_dot, u, robust