repair:
  planner: 2                      # miqp
  scenario_type: "intersection"
  ego_id: 10267
  rules: [ "R_IN4" ]
  N_r: 20            # number of time steps
debug:
  show_plots: true
  plot_limits: [45, 70, -35, -10]
