repair:
  planner: 2                      # miqp
  scenario_type: "intersection"
  ego_id: 30
  rules: [ "R_IN3_hand_draft" ]
  t_0: 0             # initial time step
  N_r: 50            # number of time steps
debug:
  show_plots: true
  plot_limits: [40, 80, -20, 20]
