debug:
  show_plots: true
  # save_plots: true
  plot_limits: [-50, 10, 3.5, 11.2]
repair:
  ego_id: 2
  rules: ["R_G2"]
  planner: 1         # qp
  t_0: 0             # initial time step
  N_r: 21            # number of time steps