version: '3.6'
services:
  planning:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/planning:humble-${architecture}-${planning}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    command: ros2 launch tum_tier4_planning_launch tier4_planning_component.launch.xml use_sim_time:=${use_sim_time}  
    healthcheck:
      test: ["CMD-SHELL", "sleep 3"]
      interval: 1s
      timeout: 5s
      retries: 2
  control:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/control:humble-${architecture}-${control}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    command: ros2 launch tum_tier4_control_launch tier4_control_component.launch.xml vehicle_model:=edgar_vehicle sensor_model:=edgar_sensor_kit use_sim_time:=${use_sim_time} 
    depends_on:
      planning:
        condition: service_healthy
  localization:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/localization:humble-${architecture}-${localization}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    command: ros2 launch tum_tier4_localization_launch tier4_localization_component.launch.xml use_sim_time:=${use_sim_time}  system_run_mode:=logging_simulation use_pointcloud_container:=true
    depends_on:
      planning:
        condition: service_healthy
  perception:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/perception:cuda-humble-${architecture}-${perception}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
      - ${model_path}:/autoware/autoware_data
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ros2 launch tum_tier4_perception_launch tier4_perception_component.launch.xml use_sim_time:=${use_sim_time}  data_path:=/autoware/autoware_data
    depends_on:
      planning:
        condition: service_healthy
  prediction:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/prediction:cuda-humble-${architecture}-${prediction}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
      - ${model_path}:/autoware/autoware_data
      - ${map_path}:/autoware_map
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: ros2 launch tum_prediction_component_launch prediction_component.launch.xml use_sim_time:=${use_sim_time}  use_vector_map:=true
    depends_on:
      planning:
        condition: service_healthy
  sensing:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/sensing:humble-${architecture}-${sensing}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    command: ros2 launch tum_tier4_sensing_launch tier4_sensing_component.launch.xml launch_sensing_driver:=false vehicle_model:=edgar_vehicle sensor_model:=edgar_sensor_kit use_pointcloud_container:=false pointcloud_container_name:=pointcloud_container use_sim_time:=${use_sim_time} 
    depends_on:
      planning:
        condition: service_healthy
  system:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/system:humble-${architecture}-${system}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    command: ros2 launch tum_tier4_system_launch tier4_system_component.launch.xml system_run_mode:=logging_simulation use_sim_time:=${use_sim_time} 
    depends_on:
      planning:
        condition: service_healthy
  vehicle:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/vehicle:humble-${architecture}-${vehicle}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    command: ros2 launch tum_tier4_vehicle_launch tier4_vehicle_component.launch.xml launch_vehicle:=true use_sim_time:=${use_sim_time} 
    depends_on:
      planning:
        condition: service_healthy
  map:
    image: gitlab.lrz.de:5005/av2.0/av_software/autoware/microservice/map:humble-${architecture}-${map}
    volumes:
      - /dev/shm:/dev/shm
      - "../config/dds/:/dev_ws/config/dds/"
      - ${map_path}:/autoware_map
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=${ROS_Domain_ID}
      - CYCLONEDDS_URI=file:///dev_ws/config/dds/${dds}.xml
    command: ros2 launch tum_tier4_map_launch tier4_map_component.launch.xml map_path:=/autoware_map use_sim_time:=${use_sim_time} 
    depends_on:
      planning:
        condition: service_healthy
